using System.Text;
using System.Text.Json;
using HelpNET.Content;
using HelpNET.Embeddings;
using HelpNET.Indexing;
using Microsoft.Extensions.AI;

namespace HelpNET.Tests.Phase4;

// ── Fake embedding generator ──────────────────────────────────────────────────

/// <summary>
/// Deterministic embedding generator for tests.
/// Each string is hashed into a unit vector in the given dimension.
/// Two identical strings will produce the same vector; similar strings will
/// produce high cosine similarity only through the hash collision path — which
/// is enough for structural tests that don't rely on semantic quality.
/// </summary>
internal sealed class FakeEmbeddingGenerator(int dimension = 4)
    : IEmbeddingGenerator<string, Embedding<float>>
{
    public EmbeddingGeneratorMetadata Metadata { get; } =
        new("fake", new Uri("fake://test"), "fake-model", dimension);

    public Task<GeneratedEmbeddings<Embedding<float>>> GenerateAsync(
        IEnumerable<string>                inputs,
        EmbeddingGenerationOptions?        options = null,
        CancellationToken                  ct      = default)
    {
        var results = inputs.Select(text =>
        {
            float[] vec = HashToUnitVector(text, dimension);
            return new Embedding<float>(vec);
        });
        return Task.FromResult(new GeneratedEmbeddings<Embedding<float>>(results.ToList()));
    }

    public object? GetService(Type serviceType, object? serviceKey = null) => null;
    public void Dispose() { }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /// <summary>Generates a repeatable L2-normalised vector from a string hash.</summary>
    internal static float[] HashToUnitVector(string text, int dim)
    {
        // Use a simple FNV-like hash to fill the vector components.
        var hash = (uint)(text.GetHashCode() ^ (text.Length * 31));
        var vec  = new float[dim];
        for (int i = 0; i < dim; i++)
        {
            hash = hash * 2654435761u + (uint)i;
            // Map [0, uint.MaxValue] → [-1, +1]
            vec[i] = (hash / (float)uint.MaxValue) * 2f - 1f;
        }
        // L2-normalise.
        float norm = MathF.Sqrt(vec.Sum(v => v * v));
        if (norm > 1e-9f)
            for (int i = 0; i < dim; i++)
                vec[i] /= norm;
        return vec;
    }
}

// ── Bundle builder ────────────────────────────────────────────────────────────

/// <summary>
/// Factory helpers to build minimal <see cref="HelpEmbeddingBundle"/> instances
/// for unit tests without touching the file system or an ONNX model.
/// </summary>
internal static class BundleBuilder
{
    internal const string TestModelId  = "test-model-v1";
    internal const int    TestDim      = 4;

    /// <summary>
    /// Builds a bundle whose embeddings are generated by <see cref="FakeEmbeddingGenerator"/>
    /// for the given <paramref name="chunks"/>.
    /// </summary>
    internal static HelpEmbeddingBundle Build(
        IReadOnlyList<HelpChunk>  chunks,
        int                       dim     = TestDim,
        string                    modelId = TestModelId)
    {
        var gen = new FakeEmbeddingGenerator(dim);

        // Generate vectors synchronously (fake generator is synchronous underneath).
        var texts   = chunks.Select(c => c.Text).ToList();
        var result  = gen.GenerateAsync(texts).GetAwaiter().GetResult();
        var vectors = result.Select(e => e.Vector.ToArray()).ToList();

        // Pack into a float32 blob.
        var blob = new byte[chunks.Count * dim * sizeof(float)];
        for (int i = 0; i < vectors.Count; i++)
        {
            float[] vec = vectors[i];
            for (int d = 0; d < dim; d++)
                BitConverter.TryWriteBytes(blob.AsSpan((i * dim + d) * sizeof(float)), vec[d]);
        }

        // Build chunk index JSON.
        var index = chunks.Select((c, i) => new
        {
            topicId    = c.TopicId,
            heading    = c.Heading,
            chunkIndex = c.Index
        }).ToList();
        string indexJson = JsonSerializer.Serialize(index);

        return new HelpEmbeddingBundle(
            modelId,
            dim,
            "deadbeef",                 // placeholder hash — not validated in tests
            new ReadOnlyMemory<byte>(blob),
            indexJson);
    }

    /// <summary>
    /// Convenience: chunk the fixture corpus and build a bundle from it.
    /// </summary>
    internal static async Task<(HelpEmbeddingBundle Bundle, HelpContentStore Store)>
        BuildFromFixtureAsync(int dim = TestDim, string modelId = TestModelId)
    {
        var store   = await TestContentFixture.LoadStoreAsync();
        var chunker = new Chunker();
        var chunks  = store.All
            .Where(t => t.IncludeInAiCorpus)
            .SelectMany(t => chunker.Chunk(t))
            .ToList();

        var bundle = Build(chunks, dim, modelId);
        return (bundle, store);
    }
}

// ── In-memory source with bundle ─────────────────────────────────────────────

/// <summary>
/// <see cref="IHelpContentSource"/> wrapper that returns a pre-built bundle.
/// </summary>
internal sealed class BundledInMemorySource(
    InMemoryHelpContentSource inner,
    HelpEmbeddingBundle?      bundle)
    : IHelpContentSource
{
    public string SourceId => inner.SourceId;

    public IAsyncEnumerable<HelpRawDocument> EnumerateAsync(CancellationToken ct)
        => inner.EnumerateAsync(ct);

    public Task<HelpEmbeddingBundle?> TryLoadEmbeddingBundleAsync(CancellationToken ct)
        => Task.FromResult(bundle);
}
