using System.Runtime.Versioning;
using System.Text;

using Windows.Win32;
using Windows.Win32.Security.Credentials;

namespace AiNET;

/// <summary>
/// <see cref="IAiSecretStore"/> backed by the <b>Windows Credential Manager</b>
/// (generic credentials, <c>CRED_PERSIST_LOCAL_MACHINE</c> scoped to the
///  current user profile).
/// </summary>
/// <remarks>
/// Secrets are encrypted at rest by the OS and are only retrievable by the
///  same user account, so no key material is written into AiNET's own JSON
///  settings. Entries are named <c>AiNET:&lt;Kind&gt;@&lt;endpoint&gt;</c> —
///  see <see cref="AiSecretKey.For(AiProviderKind, Uri?)"/>.
/// <para>
/// The P/Invoke signatures are generated by <b>CsWin32</b> from
///  <c>NativeMethods.txt</c>, following the convention used in TapeLibNET.
/// </para>
/// <para>
/// This type is Windows-only — the <c>Cred*</c> APIs it builds on are available
///  since Windows XP, hence the <c>windows5.1.2600</c> platform annotation.
///  Use <see cref="AiSecretStore.CreateDefault"/> to obtain a store that
///  transparently falls back to <see cref="InMemorySecretStore"/> on other
///  platforms.
/// </para>
/// </remarks>
[SupportedOSPlatform("windows5.1.2600")]
public sealed unsafe class CredentialManagerSecretStore : IAiSecretStore
{
    // Credential Manager limits the secret blob to 2560 bytes (CRED_MAX_CREDENTIAL_BLOB_SIZE).
    private const int MaxSecretBytes = 2560;

    /// <inheritdoc/>
    public string? Load(string key)
    {
        ArgumentException.ThrowIfNullOrEmpty(key);

        CREDENTIALW* cred = null;
        try
        {
            fixed (char* target = key)
            {
                if (!PInvoke.CredRead(target, CRED_TYPE.CRED_TYPE_GENERIC, 0, &cred) || cred is null)
                    return null;
            }

            if (cred->CredentialBlob is null || cred->CredentialBlobSize == 0)
                return null;

            return Encoding.UTF8.GetString(cred->CredentialBlob, (int)cred->CredentialBlobSize);
        }
        finally
        {
            if (cred is not null)
                PInvoke.CredFree(cred);
        }
    }

    /// <inheritdoc/>
    public bool Save(string key, string? secret)
    {
        ArgumentException.ThrowIfNullOrEmpty(key);

        if (string.IsNullOrEmpty(secret))
            return Delete(key);

        var bytes = Encoding.UTF8.GetBytes(secret);
        if (bytes.Length > MaxSecretBytes)
            throw new ArgumentException(
                $"Secret exceeds the Windows Credential Manager limit of {MaxSecretBytes} bytes.",
                nameof(secret));

        var userName = Environment.UserName;

        fixed (char* target = key)
        fixed (char* user = userName)
        fixed (byte* blob = bytes)
        {
            var cred = new CREDENTIALW
            {
                Type               = CRED_TYPE.CRED_TYPE_GENERIC,
                TargetName         = target,
                CredentialBlob     = blob,
                CredentialBlobSize = (uint)bytes.Length,
                Persist            = CRED_PERSIST.CRED_PERSIST_LOCAL_MACHINE,
                UserName           = user,
            };

            return PInvoke.CredWrite(&cred, 0);
        }
    }

    /// <inheritdoc/>
    public bool Delete(string key)
    {
        ArgumentException.ThrowIfNullOrEmpty(key);
        return DeleteCore(key);
    }

    private static bool DeleteCore(string key)
    {
        fixed (char* target = key)
            return PInvoke.CredDelete(target, CRED_TYPE.CRED_TYPE_GENERIC, 0);
    }

    /// <inheritdoc/>
    /// <remarks>
    /// Enumerates only credentials matching the <see cref="AiSecretKey.Prefix"/>
    ///  filter, so credentials belonging to other applications are never touched.
    /// </remarks>
    public void Clear()
    {
        uint count = 0;
        CREDENTIALW** creds = null;
        var filter = $"{AiSecretKey.Prefix}:*";

        fixed (char* pFilter = filter)
        {
            if (!PInvoke.CredEnumerate(pFilter, 0, &count, &creds) || creds is null)
                return;   // nothing stored (or enumeration unsupported) — nothing to do
        }

        try
        {
            // Collect the names first: deleting during enumeration would invalidate the buffer.
            var targets = new List<string>((int)count);
            for (uint i = 0; i < count; i++)
            {
                var target = creds[i]->TargetName.ToString();
                if (!string.IsNullOrEmpty(target))
                    targets.Add(target);
            }

            foreach (var target in targets)
                DeleteCore(target);
        }
        finally
        {
            PInvoke.CredFree(creds);
        }
    }
}
